# Generated by Django 3.2.15 on 2022-09-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_review_text_review_body_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Положительная оценка'), ('down', 'Отрицательная оценка')], max_length=200),
        ),
    ]
